version: '3.9'

services:
  web:
    container_name: test-verzel-container
    image: alex/verzel-web-app
    build: .
    ports:
      - "8080:5000"
    restart: always
    depends_on:
      - mysql

  mysql:
    container_name: verzel-db
    image: mysql:5.7
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: verzel
      MYSQL_USER: verzel
      MYSQL_PASSWORD: verzel
      MYSQL_ROOT_PASSWORD: verzel
    expose:
      - '3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      